// Verilated -*- C++ -*-
// DESCRIPTION: Verilator output: Design internal header
// See Vtb_xeno.h for the primary calling header

#ifndef VERILATED_VTB_XENO___024ROOT_H_
#define VERILATED_VTB_XENO___024ROOT_H_  // guard

#include "verilated.h"
#include "Vtb_xeno___024unit.h"


class Vtb_xeno__Syms;

class alignas(VL_CACHE_LINE_BYTES) Vtb_xeno___024root final {
  public:
    // CELLS
    Vtb_xeno___024unit* __PVT____024unit;

    // DESIGN SPECIFIC STATE
    // Anonymous structures to workaround compiler member-count bugs
    struct {
        VL_IN8(clk,0,0);
        VL_IN8(reset,0,0);
        VL_OUT8(r,7,0);
        VL_OUT8(g,7,0);
        VL_OUT8(b,7,0);
        VL_OUT8(hs,0,0);
        VL_OUT8(vs,0,0);
        VL_OUT8(de,0,0);
        VL_OUT8(wdt,0,0);
        VL_OUT8(dbg_as,0,0);
        VL_OUT8(dbg_irq493,0,0);
        VL_OUT8(dbg_ptm_irq,0,0);
        VL_OUT8(dbg_iack,0,0);
        VL_OUT8(dbg_phi1,0,0);
        VL_OUT8(dbg_wdt_kick,0,0);
        VL_OUT8(dbg_vsync30,0,0);
        VL_OUT8(dbg_pal_we,0,0);
        VL_OUT8(dbg_pal_addr,5,0);
        CData/*0:0*/ tb_xeno__DOT__ce_div;
        CData/*0:0*/ tb_xeno__DOT__phi_tog;
        CData/*0:0*/ tb_xeno__DOT__phi1;
        CData/*0:0*/ tb_xeno__DOT__phi2;
        CData/*1:0*/ tb_xeno__DOT__vram_we;
        CData/*1:0*/ tb_xeno__DOT__sprram_we;
        CData/*0:0*/ tb_xeno__DOT__hsync_pulse;
        CData/*0:0*/ tb_xeno__DOT__vsync30;
        CData/*0:0*/ tb_xeno__DOT__main_board__DOT__e_clk;
        CData/*0:0*/ tb_xeno__DOT__main_board__DOT__e_q;
        CData/*0:0*/ tb_xeno__DOT__main_board__DOT__e_tick;
        CData/*0:0*/ tb_xeno__DOT__main_board__DOT__bus_cycle;
        CData/*0:0*/ tb_xeno__DOT__main_board__DOT__sel_rom;
        CData/*0:0*/ tb_xeno__DOT__main_board__DOT__sel_ram;
        CData/*0:0*/ tb_xeno__DOT__main_board__DOT__sel_vram;
        CData/*0:0*/ tb_xeno__DOT__main_board__DOT__sel_spr;
        CData/*0:0*/ tb_xeno__DOT__main_board__DOT__sel_pal;
        CData/*0:0*/ tb_xeno__DOT__main_board__DOT__sel_ptm;
        CData/*0:0*/ tb_xeno__DOT__main_board__DOT__sel_wdt;
        CData/*0:0*/ tb_xeno__DOT__main_board__DOT__sel_ctl;
        CData/*0:0*/ tb_xeno__DOT__main_board__DOT__sel_in0;
        CData/*0:0*/ tb_xeno__DOT__main_board__DOT__sel_in1;
        CData/*0:0*/ tb_xeno__DOT__main_board__DOT__sel_dsw;
        CData/*0:0*/ tb_xeno__DOT__main_board__DOT__wr_q;
        CData/*0:0*/ tb_xeno__DOT__main_board__DOT__ptm_cs_q;
        CData/*0:0*/ tb_xeno__DOT__main_board__DOT__ptm_stb;
        CData/*7:0*/ tb_xeno__DOT__main_board__DOT____Vcellinp__ptm__din;
        CData/*3:0*/ tb_xeno__DOT__main_board__DOT__wdt_cnt;
        CData/*0:0*/ tb_xeno__DOT__main_board__DOT__irq493;
        CData/*0:0*/ tb_xeno__DOT__main_board__DOT__cpu__DOT__wClk;
        CData/*0:0*/ tb_xeno__DOT__main_board__DOT__cpu__DOT__enT1;
        CData/*0:0*/ tb_xeno__DOT__main_board__DOT__cpu__DOT__enT2;
        CData/*0:0*/ tb_xeno__DOT__main_board__DOT__cpu__DOT__enT3;
        CData/*0:0*/ tb_xeno__DOT__main_board__DOT__cpu__DOT__enT4;
        CData/*0:0*/ tb_xeno__DOT__main_board__DOT__cpu__DOT__rDtack;
        CData/*0:0*/ tb_xeno__DOT__main_board__DOT__cpu__DOT__rBerr;
        CData/*2:0*/ tb_xeno__DOT__main_board__DOT__cpu__DOT__rIpl;
        CData/*2:0*/ tb_xeno__DOT__main_board__DOT__cpu__DOT__iIpl;
        CData/*0:0*/ tb_xeno__DOT__main_board__DOT__cpu__DOT__Vpai;
        CData/*0:0*/ tb_xeno__DOT__main_board__DOT__cpu__DOT__BeI;
        CData/*0:0*/ tb_xeno__DOT__main_board__DOT__cpu__DOT__Halti;
        CData/*0:0*/ tb_xeno__DOT__main_board__DOT__cpu__DOT__BRi;
        CData/*0:0*/ tb_xeno__DOT__main_board__DOT__cpu__DOT__BgackI;
        CData/*0:0*/ tb_xeno__DOT__main_board__DOT__cpu__DOT__BeiDelay;
        CData/*0:0*/ tb_xeno__DOT__main_board__DOT__cpu__DOT__rstUrom;
        CData/*0:0*/ tb_xeno__DOT__main_board__DOT__cpu__DOT____Vcellinp__nanoRom__clk;
    };
    struct {
        CData/*0:0*/ tb_xeno__DOT__main_board__DOT__cpu__DOT__Tpend;
        CData/*0:0*/ tb_xeno__DOT__main_board__DOT__cpu__DOT__intPend;
        CData/*0:0*/ tb_xeno__DOT__main_board__DOT__cpu__DOT__pswT;
        CData/*0:0*/ tb_xeno__DOT__main_board__DOT__cpu__DOT__pswS;
        CData/*2:0*/ tb_xeno__DOT__main_board__DOT__cpu__DOT__pswI;
        CData/*0:0*/ tb_xeno__DOT__main_board__DOT__cpu__DOT__dcr4;
        CData/*0:0*/ tb_xeno__DOT__main_board__DOT__cpu__DOT__isLineA;
        CData/*0:0*/ tb_xeno__DOT__main_board__DOT__cpu__DOT__isLineF;
        CData/*3:0*/ tb_xeno__DOT__main_board__DOT__cpu__DOT__tvn;
        CData/*0:0*/ tb_xeno__DOT__main_board__DOT__cpu__DOT__busAddrErr;
        CData/*0:0*/ tb_xeno__DOT__main_board__DOT__cpu__DOT__addrOe;
        CData/*0:0*/ tb_xeno__DOT__main_board__DOT__cpu__DOT__iStop;
        CData/*0:0*/ tb_xeno__DOT__main_board__DOT__cpu__DOT__A0Err;
        CData/*0:0*/ tb_xeno__DOT__main_board__DOT__cpu__DOT__excRst;
        CData/*0:0*/ tb_xeno__DOT__main_board__DOT__cpu__DOT__BerrA;
        CData/*0:0*/ tb_xeno__DOT__main_board__DOT__cpu__DOT__Spuria;
        CData/*0:0*/ tb_xeno__DOT__main_board__DOT__cpu__DOT__Avia;
        CData/*0:0*/ tb_xeno__DOT__main_board__DOT__cpu__DOT__rAddrErr;
        CData/*0:0*/ tb_xeno__DOT__main_board__DOT__cpu__DOT__iBusErr;
        CData/*0:0*/ tb_xeno__DOT__main_board__DOT__cpu__DOT__Err6591;
        CData/*0:0*/ tb_xeno__DOT__main_board__DOT__cpu__DOT__iAddrErr;
        CData/*0:0*/ tb_xeno__DOT__main_board__DOT__cpu__DOT__enErrClk;
        CData/*2:0*/ tb_xeno__DOT__main_board__DOT__cpu__DOT__rFC;
        CData/*2:0*/ tb_xeno__DOT__main_board__DOT__cpu__DOT__inl;
        CData/*0:0*/ tb_xeno__DOT__main_board__DOT__cpu__DOT__updIll;
        CData/*0:0*/ tb_xeno__DOT__main_board__DOT__cpu__DOT__prevNmi;
        CData/*0:0*/ tb_xeno__DOT__main_board__DOT__cpu__DOT__iplStable;
        CData/*0:0*/ tb_xeno__DOT__main_board__DOT__cpu__DOT__iplComp;
        CData/*3:0*/ tb_xeno__DOT__main_board__DOT__cpu__DOT__eCntr;
        CData/*0:0*/ tb_xeno__DOT__main_board__DOT__cpu__DOT__rVma;
        CData/*0:0*/ tb_xeno__DOT__main_board__DOT__cpu__DOT__irdToCcr_t4;
        CData/*4:0*/ tb_xeno__DOT__main_board__DOT__cpu__DOT__ssw;
        CData/*3:0*/ tb_xeno__DOT__main_board__DOT__cpu__DOT__tvnLatch;
        CData/*0:0*/ tb_xeno__DOT__main_board__DOT__cpu__DOT__inExcept01;
        CData/*0:0*/ tb_xeno__DOT__main_board__DOT__cpu__DOT__excUnit__DOT__abdIsByte;
        CData/*0:0*/ tb_xeno__DOT__main_board__DOT__cpu__DOT__excUnit__DOT__Pcl2Dbl;
        CData/*0:0*/ tb_xeno__DOT__main_board__DOT__cpu__DOT__excUnit__DOT__Pch2Dbh;
        CData/*0:0*/ tb_xeno__DOT__main_board__DOT__cpu__DOT__excUnit__DOT__Pcl2Abl;
        CData/*0:0*/ tb_xeno__DOT__main_board__DOT__cpu__DOT__excUnit__DOT__Pch2Abh;
        CData/*4:0*/ tb_xeno__DOT__main_board__DOT__cpu__DOT__excUnit__DOT__actualRx;
        CData/*4:0*/ tb_xeno__DOT__main_board__DOT__cpu__DOT__excUnit__DOT__actualRy;
        CData/*3:0*/ tb_xeno__DOT__main_board__DOT__cpu__DOT__excUnit__DOT__movemRx;
        CData/*0:0*/ tb_xeno__DOT__main_board__DOT__cpu__DOT__excUnit__DOT__byteNotSpAlign;
        CData/*4:0*/ tb_xeno__DOT__main_board__DOT__cpu__DOT__excUnit__DOT__rxMux;
        CData/*4:0*/ tb_xeno__DOT__main_board__DOT__cpu__DOT__excUnit__DOT__ryMux;
        CData/*3:0*/ tb_xeno__DOT__main_board__DOT__cpu__DOT__excUnit__DOT__rxReg;
        CData/*3:0*/ tb_xeno__DOT__main_board__DOT__cpu__DOT__excUnit__DOT__ryReg;
        CData/*0:0*/ tb_xeno__DOT__main_board__DOT__cpu__DOT__excUnit__DOT__rxIsSp;
        CData/*0:0*/ tb_xeno__DOT__main_board__DOT__cpu__DOT__excUnit__DOT__ryIsSp;
        CData/*0:0*/ tb_xeno__DOT__main_board__DOT__cpu__DOT__excUnit__DOT__rxIsAreg;
        CData/*0:0*/ tb_xeno__DOT__main_board__DOT__cpu__DOT__excUnit__DOT__ryIsAreg;
        CData/*0:0*/ tb_xeno__DOT__main_board__DOT__cpu__DOT__excUnit__DOT__ryl2Abl;
        CData/*0:0*/ tb_xeno__DOT__main_board__DOT__cpu__DOT__excUnit__DOT__ryl2Abd;
        CData/*0:0*/ tb_xeno__DOT__main_board__DOT__cpu__DOT__excUnit__DOT__ryl2Dbl;
        CData/*0:0*/ tb_xeno__DOT__main_board__DOT__cpu__DOT__excUnit__DOT__ryl2Dbd;
        CData/*0:0*/ tb_xeno__DOT__main_board__DOT__cpu__DOT__excUnit__DOT__rxl2Abl;
        CData/*0:0*/ tb_xeno__DOT__main_board__DOT__cpu__DOT__excUnit__DOT__rxl2Abd;
        CData/*0:0*/ tb_xeno__DOT__main_board__DOT__cpu__DOT__excUnit__DOT__rxl2Dbl;
        CData/*0:0*/ tb_xeno__DOT__main_board__DOT__cpu__DOT__excUnit__DOT__rxl2Dbd;
        CData/*0:0*/ tb_xeno__DOT__main_board__DOT__cpu__DOT__excUnit__DOT__abhIdle;
        CData/*0:0*/ tb_xeno__DOT__main_board__DOT__cpu__DOT__excUnit__DOT__ablIdle;
        CData/*0:0*/ tb_xeno__DOT__main_board__DOT__cpu__DOT__excUnit__DOT__abdIdle;
        CData/*0:0*/ tb_xeno__DOT__main_board__DOT__cpu__DOT__excUnit__DOT__dbhIdle;
        CData/*0:0*/ tb_xeno__DOT__main_board__DOT__cpu__DOT__excUnit__DOT__dblIdle;
    };
    struct {
        CData/*0:0*/ tb_xeno__DOT__main_board__DOT__cpu__DOT__excUnit__DOT__dbdIdle;
        CData/*0:0*/ tb_xeno__DOT__main_board__DOT__cpu__DOT__excUnit__DOT__dbl2Pcl;
        CData/*0:0*/ tb_xeno__DOT__main_board__DOT__cpu__DOT__excUnit__DOT__dbh2Pch;
        CData/*0:0*/ tb_xeno__DOT__main_board__DOT__cpu__DOT__excUnit__DOT__abh2Pch;
        CData/*0:0*/ tb_xeno__DOT__main_board__DOT__cpu__DOT__excUnit__DOT__abl2Pcl;
        CData/*3:0*/ tb_xeno__DOT__main_board__DOT__cpu__DOT__excUnit__DOT__prHbit;
        CData/*4:0*/ tb_xeno__DOT__main_board__DOT__cpu__DOT__excUnit__DOT__alu__DOT__pswCcr;
        CData/*4:0*/ tb_xeno__DOT__main_board__DOT__cpu__DOT__excUnit__DOT__alu__DOT__ccrCore;
        CData/*4:0*/ tb_xeno__DOT__main_board__DOT__cpu__DOT__excUnit__DOT__alu__DOT__ccrTemp;
        CData/*0:0*/ tb_xeno__DOT__main_board__DOT__cpu__DOT__excUnit__DOT__alu__DOT__coreH;
        CData/*0:0*/ tb_xeno__DOT__main_board__DOT__cpu__DOT__excUnit__DOT__alu__DOT__subHcarry;
        CData/*0:0*/ tb_xeno__DOT__main_board__DOT__cpu__DOT__excUnit__DOT__alu__DOT__isArX;
        CData/*0:0*/ tb_xeno__DOT__main_board__DOT__cpu__DOT__excUnit__DOT__alu__DOT__noCcrEn;
        CData/*0:0*/ tb_xeno__DOT__main_board__DOT__cpu__DOT__excUnit__DOT__alu__DOT__isByte;
        CData/*4:0*/ tb_xeno__DOT__main_board__DOT__cpu__DOT__excUnit__DOT__alu__DOT__ccrMask;
        CData/*4:0*/ tb_xeno__DOT__main_board__DOT__cpu__DOT__excUnit__DOT__alu__DOT__oper;
        CData/*4:0*/ tb_xeno__DOT__main_board__DOT__cpu__DOT__excUnit__DOT__alu__DOT__cMask;
        CData/*4:0*/ tb_xeno__DOT__main_board__DOT__cpu__DOT__excUnit__DOT__alu__DOT__aluOp;
        CData/*7:0*/ tb_xeno__DOT__main_board__DOT__cpu__DOT__excUnit__DOT__alu__DOT__bcdLatch;
        CData/*0:0*/ tb_xeno__DOT__main_board__DOT__cpu__DOT__excUnit__DOT__alu__DOT__bcdCarry;
        CData/*0:0*/ tb_xeno__DOT__main_board__DOT__cpu__DOT__excUnit__DOT__alu__DOT__bcdOverf;
        CData/*0:0*/ tb_xeno__DOT__main_board__DOT__cpu__DOT__excUnit__DOT__alu__DOT__isLong;
        CData/*0:0*/ tb_xeno__DOT__main_board__DOT__cpu__DOT__excUnit__DOT__alu__DOT__rIrd8;
        CData/*0:0*/ tb_xeno__DOT__main_board__DOT__cpu__DOT__excUnit__DOT__alu__DOT__isShift;
        CData/*0:0*/ tb_xeno__DOT__main_board__DOT__cpu__DOT__excUnit__DOT__alu__DOT__shftRight;
        CData/*0:0*/ tb_xeno__DOT__main_board__DOT__cpu__DOT__excUnit__DOT__alu__DOT____Vcellinp__shifter__swapWords;
        CData/*4:0*/ tb_xeno__DOT__main_board__DOT__cpu__DOT__excUnit__DOT__alu__DOT__aluCorf__DOT__hNib;
        CData/*1:0*/ tb_xeno__DOT__main_board__DOT__cpu__DOT__excUnit__DOT__alu__DOT__rowDecoder__DOT__unnamedblk1__DOT__stype;
        CData/*0:0*/ tb_xeno__DOT__main_board__DOT__cpu__DOT__excUnit__DOT__dataIo__DOT__xToDbin;
        CData/*0:0*/ tb_xeno__DOT__main_board__DOT__cpu__DOT__excUnit__DOT__dataIo__DOT__xToIrc;
        CData/*0:0*/ tb_xeno__DOT__main_board__DOT__cpu__DOT__excUnit__DOT__dataIo__DOT__dbinNoLow;
        CData/*0:0*/ tb_xeno__DOT__main_board__DOT__cpu__DOT__excUnit__DOT__dataIo__DOT__dbinNoHigh;
        CData/*0:0*/ tb_xeno__DOT__main_board__DOT__cpu__DOT__excUnit__DOT__dataIo__DOT__byteMux;
        CData/*0:0*/ tb_xeno__DOT__main_board__DOT__cpu__DOT__excUnit__DOT__dataIo__DOT__isByte_T4;
        CData/*0:0*/ tb_xeno__DOT__main_board__DOT__cpu__DOT__excUnit__DOT__dataIo__DOT__byteCycle;
        CData/*0:0*/ tb_xeno__DOT__main_board__DOT__cpu__DOT__busArbiter__DOT__rGranted;
        CData/*0:0*/ tb_xeno__DOT__main_board__DOT__cpu__DOT__busControl__DOT__rAS;
        CData/*0:0*/ tb_xeno__DOT__main_board__DOT__cpu__DOT__busControl__DOT__rLDS;
        CData/*0:0*/ tb_xeno__DOT__main_board__DOT__cpu__DOT__busControl__DOT__rUDS;
        CData/*0:0*/ tb_xeno__DOT__main_board__DOT__cpu__DOT__busControl__DOT__rRWn;
        CData/*0:0*/ tb_xeno__DOT__main_board__DOT__cpu__DOT__busControl__DOT__bcPend;
        CData/*0:0*/ tb_xeno__DOT__main_board__DOT__cpu__DOT__busControl__DOT__isWriteReg;
        CData/*0:0*/ tb_xeno__DOT__main_board__DOT__cpu__DOT__busControl__DOT__bciByte;
        CData/*0:0*/ tb_xeno__DOT__main_board__DOT__cpu__DOT__busControl__DOT__isRmcReg;
        CData/*0:0*/ tb_xeno__DOT__main_board__DOT__cpu__DOT__busControl__DOT__wendReg;
        CData/*0:0*/ tb_xeno__DOT__main_board__DOT__cpu__DOT__busControl__DOT__addrOeDelay;
        CData/*0:0*/ tb_xeno__DOT__main_board__DOT__cpu__DOT__busControl__DOT__isByteT4;
        CData/*0:0*/ tb_xeno__DOT__main_board__DOT__cpu__DOT__busControl__DOT__bcReset;
        CData/*0:0*/ tb_xeno__DOT__main_board__DOT__cpu__DOT__busControl__DOT__busEnding;
        CData/*3:0*/ tb_xeno__DOT__main_board__DOT__cpu__DOT__nDecoder__DOT__ftuCtrl;
        CData/*1:0*/ tb_xeno__DOT__main_board__DOT__cpu__DOT__nDecoder__DOT__dobCtrl;
        CData/*0:0*/ tb_xeno__DOT__main_board__DOT__cpu__DOT__nDecoder__DOT__dblSpecial;
        CData/*0:0*/ tb_xeno__DOT__main_board__DOT__cpu__DOT__nDecoder__DOT__dbhSpecial;
        CData/*0:0*/ tb_xeno__DOT__main_board__DOT__cpu__DOT__nDecoder__DOT__ablSpecial;
        CData/*0:0*/ tb_xeno__DOT__main_board__DOT__cpu__DOT__nDecoder__DOT__abhSpecial;
        CData/*0:0*/ tb_xeno__DOT__main_board__DOT__cpu__DOT__nDecoder__DOT__isPcRel;
        CData/*1:0*/ tb_xeno__DOT__main_board__DOT__cpu__DOT__sequencer__DOT__c0c1;
        CData/*0:0*/ tb_xeno__DOT__main_board__DOT__cpu__DOT__sequencer__DOT__a0Rst;
        CData/*1:0*/ tb_xeno__DOT__main_board__DOT__cpu__DOT__sequencer__DOT__enl;
        CData/*0:0*/ tb_xeno__DOT__main_board__DOT__cpu__DOT__sequencer__DOT__ccTest;
        CData/*0:0*/ tb_xeno__DOT__main_board__DOT__cpu__DOT__sequencer__DOT__rTrace;
        CData/*0:0*/ tb_xeno__DOT__main_board__DOT__cpu__DOT__sequencer__DOT__rInterrupt;
        CData/*0:0*/ tb_xeno__DOT__main_board__DOT__cpu__DOT__sequencer__DOT__rIllegal;
        CData/*0:0*/ tb_xeno__DOT__main_board__DOT__cpu__DOT__sequencer__DOT__rPriv;
    };
    struct {
        CData/*0:0*/ tb_xeno__DOT__main_board__DOT__cpu__DOT__sequencer__DOT__rLineA;
        CData/*0:0*/ tb_xeno__DOT__main_board__DOT__cpu__DOT__sequencer__DOT__rLineF;
        CData/*0:0*/ tb_xeno__DOT__main_board__DOT__cpu__DOT__sequencer__DOT__rExcRst;
        CData/*0:0*/ tb_xeno__DOT__main_board__DOT__cpu__DOT__sequencer__DOT__rExcAdrErr;
        CData/*0:0*/ tb_xeno__DOT__main_board__DOT__cpu__DOT__sequencer__DOT__rExcBusErr;
        CData/*0:0*/ tb_xeno__DOT__main_board__DOT__cpu__DOT__sequencer__DOT__rSpurious;
        CData/*0:0*/ tb_xeno__DOT__main_board__DOT__cpu__DOT__sequencer__DOT__rAutovec;
        CData/*0:0*/ tb_xeno__DOT__main_board__DOT__cpu__DOT__sequencer__DOT__grp1LatchEn;
        CData/*0:0*/ tb_xeno__DOT__main_board__DOT__cpu__DOT__sequencer__DOT__grp0LatchEn;
        CData/*2:0*/ tb_xeno__DOT__main_board__DOT__ptm__DOT__flag;
        CData/*2:0*/ tb_xeno__DOT__main_board__DOT__ptm__DOT__flag_read;
        CData/*7:0*/ tb_xeno__DOT__main_board__DOT__ptm__DOT__msb_buf;
        CData/*2:0*/ tb_xeno__DOT__main_board__DOT__ptm__DOT__c_q;
        CData/*2:0*/ tb_xeno__DOT__main_board__DOT__ptm__DOT__t3_pre;
        CData/*2:0*/ tb_xeno__DOT__main_board__DOT__ptm__DOT__oneshot_done;
        CData/*2:0*/ tb_xeno__DOT__main_board__DOT__ptm__DOT__c_in;
        CData/*0:0*/ tb_xeno__DOT__main_board__DOT__ptm__DOT__t1_reset;
        CData/*2:0*/ tb_xeno__DOT__main_board__DOT__ptm__DOT__tick;
        CData/*3:0*/ tb_xeno__DOT__video__DOT____VlemCall_0__bg_pen;
        CData/*0:0*/ tb_xeno__DOT__video__DOT__field;
        CData/*0:0*/ tb_xeno__DOT__video__DOT__bg_rhalf;
        CData/*0:0*/ tb_xeno__DOT__video__DOT__lbuf_sel;
        CData/*0:0*/ tb_xeno__DOT__video__DOT__bg_wrbuf;
        CData/*0:0*/ tb_xeno__DOT__video__DOT__sp_wrbuf;
        CData/*6:0*/ tb_xeno__DOT__video__DOT__bg_disp_q;
        CData/*3:0*/ tb_xeno__DOT__video__DOT__bg_st;
        CData/*4:0*/ tb_xeno__DOT__video__DOT__bg_cell;
        CData/*3:0*/ tb_xeno__DOT__video__DOT__bg_px;
        CData/*3:0*/ tb_xeno__DOT__video__DOT__sp_st;
        CData/*7:0*/ tb_xeno__DOT__video__DOT__sp_y;
        CData/*7:0*/ tb_xeno__DOT__video__DOT__sp_flags;
        CData/*7:0*/ tb_xeno__DOT__video__DOT__sp_code_lo;
        CData/*7:0*/ tb_xeno__DOT__video__DOT__sp_x;
        CData/*2:0*/ tb_xeno__DOT__video__DOT__sp_fetch_cnt;
        CData/*5:0*/ tb_xeno__DOT__video__DOT__sp_px;
        CData/*0:0*/ tb_xeno__DOT__video__DOT__yt_hit;
        CData/*3:0*/ tb_xeno__DOT__video__DOT__sp_pval;
        CData/*0:0*/ tb_xeno__DOT__video__DOT__sp_xok;
        CData/*7:0*/ tb_xeno__DOT__video__DOT__unnamedblk3__DOT__cls;
        CData/*5:0*/ tb_xeno__DOT__video__DOT__unnamedblk4__DOT__idx;
        CData/*7:0*/ tb_xeno__DOT__video__DOT__unnamedblk4__DOT__eff;
        CData/*0:0*/ tb_xeno__DOT__video__DOT__unnamedblk4__DOT__eff_hi;
        CData/*0:0*/ __Vtask_tb_xeno__DOT__main_board__DOT__cpu__DOT__excUnit__DOT__alu__DOT__mySubber__0__cout;
        CData/*4:0*/ __VdfgRegularize_hebeb780c_0_2;
        CData/*1:0*/ __VdfgRegularize_hebeb780c_0_5;
        CData/*4:0*/ __VdfgRegularize_hebeb780c_0_8;
        CData/*4:0*/ __VdfgRegularize_hebeb780c_0_10;
        CData/*4:0*/ __VdfgRegularize_hebeb780c_0_14;
        CData/*0:0*/ __Vdly__tb_xeno__DOT__ce_div;
        CData/*0:0*/ __Vdly__tb_xeno__DOT__video__DOT__field;
        CData/*0:0*/ __VdlySet__tb_xeno__DOT__main_board__DOT__cpu__DOT__excUnit__DOT__regs68L__v0;
        CData/*0:0*/ __VdlySet__tb_xeno__DOT__main_board__DOT__cpu__DOT__excUnit__DOT__regs68H__v0;
        CData/*0:0*/ __VdlySet__tb_xeno__DOT__main_board__DOT__cpu__DOT__excUnit__DOT__regs68L__v1;
        CData/*0:0*/ __VdlySet__tb_xeno__DOT__main_board__DOT__cpu__DOT__excUnit__DOT__regs68H__v1;
        CData/*0:0*/ __VdlySet__tb_xeno__DOT__main_board__DOT__cpu__DOT__excUnit__DOT__regs68L__v2;
        CData/*0:0*/ __VdlySet__tb_xeno__DOT__main_board__DOT__cpu__DOT__excUnit__DOT__regs68H__v2;
        CData/*0:0*/ __VdlySet__tb_xeno__DOT__main_board__DOT__cpu__DOT__excUnit__DOT__regs68L__v3;
        CData/*0:0*/ __VdlySet__tb_xeno__DOT__main_board__DOT__cpu__DOT__excUnit__DOT__regs68H__v3;
        CData/*0:0*/ __VdlySet__tb_xeno__DOT__main_board__DOT__cpu__DOT__excUnit__DOT__regs68L__v4;
        CData/*0:0*/ __VdlySet__tb_xeno__DOT__main_board__DOT__cpu__DOT__excUnit__DOT__regs68H__v4;
        CData/*0:0*/ __VdlySet__tb_xeno__DOT__main_board__DOT__cpu__DOT__excUnit__DOT__regs68L__v5;
        CData/*0:0*/ __VdlySet__tb_xeno__DOT__main_board__DOT__cpu__DOT__excUnit__DOT__regs68H__v5;
        CData/*0:0*/ __VdlySet__tb_xeno__DOT__main_board__DOT__cpu__DOT__excUnit__DOT__regs68L__v6;
        CData/*0:0*/ __VdlySet__tb_xeno__DOT__main_board__DOT__cpu__DOT__excUnit__DOT__regs68H__v6;
    };
    struct {
        CData/*0:0*/ __VdlySet__tb_xeno__DOT__main_board__DOT__cpu__DOT__excUnit__DOT__regs68L__v7;
        CData/*0:0*/ __VdlySet__tb_xeno__DOT__main_board__DOT__cpu__DOT__excUnit__DOT__regs68H__v7;
        CData/*0:0*/ __VdlySet__tb_xeno__DOT__main_board__DOT__cpu__DOT__excUnit__DOT__regs68L__v8;
        CData/*0:0*/ __VdlySet__tb_xeno__DOT__main_board__DOT__cpu__DOT__excUnit__DOT__regs68H__v8;
        CData/*0:0*/ __VdlySet__tb_xeno__DOT__main_board__DOT__cpu__DOT__excUnit__DOT__regs68L__v9;
        CData/*0:0*/ __VdlySet__tb_xeno__DOT__main_board__DOT__cpu__DOT__excUnit__DOT__regs68H__v9;
        CData/*0:0*/ __VdlySet__tb_xeno__DOT__main_board__DOT__cpu__DOT__excUnit__DOT__regs68L__v10;
        CData/*0:0*/ __VdlySet__tb_xeno__DOT__main_board__DOT__cpu__DOT__excUnit__DOT__regs68H__v10;
        CData/*0:0*/ __VdlySet__tb_xeno__DOT__main_board__DOT__cpu__DOT__excUnit__DOT__regs68L__v11;
        CData/*0:0*/ __VdlySet__tb_xeno__DOT__main_board__DOT__cpu__DOT__excUnit__DOT__regs68H__v11;
        CData/*0:0*/ __VdlySet__tb_xeno__DOT__main_board__DOT__cpu__DOT__excUnit__DOT__regs68L__v12;
        CData/*0:0*/ __VdlySet__tb_xeno__DOT__main_board__DOT__cpu__DOT__excUnit__DOT__regs68H__v12;
        CData/*0:0*/ __VdlySet__tb_xeno__DOT__main_board__DOT__cpu__DOT__excUnit__DOT__regs68L__v13;
        CData/*0:0*/ __VdlySet__tb_xeno__DOT__main_board__DOT__cpu__DOT__excUnit__DOT__regs68H__v13;
        CData/*0:0*/ __VdlySet__tb_xeno__DOT__main_board__DOT__cpu__DOT__excUnit__DOT__regs68L__v14;
        CData/*0:0*/ __VdlySet__tb_xeno__DOT__main_board__DOT__cpu__DOT__excUnit__DOT__regs68H__v14;
        CData/*0:0*/ __VdlySet__tb_xeno__DOT__main_board__DOT__cpu__DOT__excUnit__DOT__regs68L__v15;
        CData/*0:0*/ __VdlySet__tb_xeno__DOT__main_board__DOT__cpu__DOT__excUnit__DOT__regs68H__v15;
        CData/*0:0*/ __VdlySet__tb_xeno__DOT__main_board__DOT__cpu__DOT__excUnit__DOT__regs68L__v16;
        CData/*0:0*/ __VdlySet__tb_xeno__DOT__main_board__DOT__cpu__DOT__excUnit__DOT__regs68H__v16;
        CData/*0:0*/ __VdlySet__tb_xeno__DOT__main_board__DOT__cpu__DOT__excUnit__DOT__regs68L__v17;
        CData/*0:0*/ __VdlySet__tb_xeno__DOT__main_board__DOT__cpu__DOT__excUnit__DOT__regs68H__v17;
        CData/*4:0*/ __VdlyDim0__tb_xeno__DOT__main_board__DOT__cpu__DOT__excUnit__DOT__regs68H__v18;
        CData/*0:0*/ __VdlySet__tb_xeno__DOT__main_board__DOT__cpu__DOT__excUnit__DOT__regs68H__v18;
        CData/*4:0*/ __VdlyDim0__tb_xeno__DOT__main_board__DOT__cpu__DOT__excUnit__DOT__regs68H__v19;
        CData/*0:0*/ __VdlySet__tb_xeno__DOT__main_board__DOT__cpu__DOT__excUnit__DOT__regs68H__v19;
        CData/*4:0*/ __VdlyDim0__tb_xeno__DOT__main_board__DOT__cpu__DOT__excUnit__DOT__regs68L__v18;
        CData/*0:0*/ __VdlySet__tb_xeno__DOT__main_board__DOT__cpu__DOT__excUnit__DOT__regs68L__v18;
        CData/*4:0*/ __VdlyDim0__tb_xeno__DOT__main_board__DOT__cpu__DOT__excUnit__DOT__regs68L__v19;
        CData/*0:0*/ __VdlySet__tb_xeno__DOT__main_board__DOT__cpu__DOT__excUnit__DOT__regs68L__v19;
        CData/*7:0*/ __VdlyVal__tb_xeno__DOT__main_board__DOT__cpu__DOT__excUnit__DOT__regs68L__v20;
        CData/*4:0*/ __VdlyDim0__tb_xeno__DOT__main_board__DOT__cpu__DOT__excUnit__DOT__regs68L__v20;
        CData/*0:0*/ __VdlySet__tb_xeno__DOT__main_board__DOT__cpu__DOT__excUnit__DOT__regs68L__v20;
        CData/*4:0*/ __VdlyDim0__tb_xeno__DOT__main_board__DOT__cpu__DOT__excUnit__DOT__regs68L__v21;
        CData/*0:0*/ __VdlySet__tb_xeno__DOT__main_board__DOT__cpu__DOT__excUnit__DOT__regs68L__v21;
        CData/*4:0*/ __VdlyDim0__tb_xeno__DOT__main_board__DOT__cpu__DOT__excUnit__DOT__regs68L__v22;
        CData/*0:0*/ __VdlySet__tb_xeno__DOT__main_board__DOT__cpu__DOT__excUnit__DOT__regs68L__v22;
        CData/*4:0*/ __VdlyDim0__tb_xeno__DOT__main_board__DOT__cpu__DOT__excUnit__DOT__regs68L__v23;
        CData/*0:0*/ __VdlySet__tb_xeno__DOT__main_board__DOT__cpu__DOT__excUnit__DOT__regs68L__v23;
        CData/*7:0*/ __VdlyVal__tb_xeno__DOT__main_board__DOT__cpu__DOT__excUnit__DOT__regs68L__v24;
        CData/*4:0*/ __VdlyDim0__tb_xeno__DOT__main_board__DOT__cpu__DOT__excUnit__DOT__regs68L__v24;
        CData/*0:0*/ __VdlySet__tb_xeno__DOT__main_board__DOT__cpu__DOT__excUnit__DOT__regs68L__v24;
        CData/*4:0*/ __VdlyDim0__tb_xeno__DOT__main_board__DOT__cpu__DOT__excUnit__DOT__regs68L__v25;
        CData/*0:0*/ __VdlySet__tb_xeno__DOT__main_board__DOT__cpu__DOT__excUnit__DOT__regs68L__v25;
        CData/*0:0*/ __VdlyVal__tb_xeno__DOT__main_board__DOT__cpu__DOT__Nanod__v0;
        CData/*0:0*/ __VdlySet__tb_xeno__DOT__main_board__DOT__cpu__DOT__Nanod__v0;
        CData/*2:0*/ __VdlyVal__tb_xeno__DOT__main_board__DOT__cpu__DOT__Nanod__v1;
        CData/*0:0*/ __VdlySet__tb_xeno__DOT__main_board__DOT__cpu__DOT__Nanod__v1;
        CData/*0:0*/ __VdlyVal__tb_xeno__DOT__main_board__DOT__cpu__DOT__Nanod__v2;
        CData/*0:0*/ __VdlySet__tb_xeno__DOT__main_board__DOT__cpu__DOT__Nanod__v2;
        CData/*0:0*/ __VdlyVal__tb_xeno__DOT__main_board__DOT__cpu__DOT__Nanod__v3;
        CData/*0:0*/ __VdlySet__tb_xeno__DOT__main_board__DOT__cpu__DOT__Nanod__v3;
        CData/*0:0*/ __VdlyVal__tb_xeno__DOT__main_board__DOT__cpu__DOT__Nanod__v4;
        CData/*0:0*/ __VdlySet__tb_xeno__DOT__main_board__DOT__cpu__DOT__Nanod__v4;
        CData/*0:0*/ __VdlyVal__tb_xeno__DOT__main_board__DOT__cpu__DOT__Nanod__v5;
        CData/*0:0*/ __VdlySet__tb_xeno__DOT__main_board__DOT__cpu__DOT__Nanod__v5;
        CData/*0:0*/ __VdlyVal__tb_xeno__DOT__main_board__DOT__cpu__DOT__Nanod__v6;
        CData/*0:0*/ __VdlySet__tb_xeno__DOT__main_board__DOT__cpu__DOT__Nanod__v6;
        CData/*0:0*/ __VdlyVal__tb_xeno__DOT__main_board__DOT__cpu__DOT__Nanod__v7;
        CData/*0:0*/ __VdlySet__tb_xeno__DOT__main_board__DOT__cpu__DOT__Nanod__v7;
        CData/*0:0*/ __VdlyVal__tb_xeno__DOT__main_board__DOT__cpu__DOT__Nanod__v8;
        CData/*0:0*/ __VdlySet__tb_xeno__DOT__main_board__DOT__cpu__DOT__Nanod__v8;
        CData/*0:0*/ __VdlyVal__tb_xeno__DOT__main_board__DOT__cpu__DOT__Nanod__v9;
        CData/*0:0*/ __VdlySet__tb_xeno__DOT__main_board__DOT__cpu__DOT__Nanod__v9;
    };
    struct {
        CData/*0:0*/ __VdlyVal__tb_xeno__DOT__main_board__DOT__cpu__DOT__Nanod__v10;
        CData/*0:0*/ __VdlySet__tb_xeno__DOT__main_board__DOT__cpu__DOT__Nanod__v10;
        CData/*0:0*/ __VdlyVal__tb_xeno__DOT__main_board__DOT__cpu__DOT__Nanod__v11;
        CData/*0:0*/ __VdlySet__tb_xeno__DOT__main_board__DOT__cpu__DOT__Nanod__v11;
        CData/*0:0*/ __VdlyVal__tb_xeno__DOT__main_board__DOT__cpu__DOT__Nanod__v12;
        CData/*0:0*/ __VdlySet__tb_xeno__DOT__main_board__DOT__cpu__DOT__Nanod__v12;
        CData/*0:0*/ __VdlyVal__tb_xeno__DOT__main_board__DOT__cpu__DOT__Nanod__v13;
        CData/*0:0*/ __VdlySet__tb_xeno__DOT__main_board__DOT__cpu__DOT__Nanod__v13;
        CData/*0:0*/ __VdlyVal__tb_xeno__DOT__main_board__DOT__cpu__DOT__Nanod__v14;
        CData/*0:0*/ __VdlySet__tb_xeno__DOT__main_board__DOT__cpu__DOT__Nanod__v14;
        CData/*0:0*/ __VdlyVal__tb_xeno__DOT__main_board__DOT__cpu__DOT__Nanod__v15;
        CData/*0:0*/ __VdlySet__tb_xeno__DOT__main_board__DOT__cpu__DOT__Nanod__v15;
        CData/*0:0*/ __VdlyVal__tb_xeno__DOT__main_board__DOT__cpu__DOT__Nanod__v16;
        CData/*0:0*/ __VdlySet__tb_xeno__DOT__main_board__DOT__cpu__DOT__Nanod__v16;
        CData/*0:0*/ __VdlyVal__tb_xeno__DOT__main_board__DOT__cpu__DOT__Nanod__v17;
        CData/*0:0*/ __VdlySet__tb_xeno__DOT__main_board__DOT__cpu__DOT__Nanod__v17;
        CData/*0:0*/ __VdlyVal__tb_xeno__DOT__main_board__DOT__cpu__DOT__Nanod__v18;
        CData/*0:0*/ __VdlySet__tb_xeno__DOT__main_board__DOT__cpu__DOT__Nanod__v18;
        CData/*0:0*/ __VdlyVal__tb_xeno__DOT__main_board__DOT__cpu__DOT__Nanod__v19;
        CData/*0:0*/ __VdlySet__tb_xeno__DOT__main_board__DOT__cpu__DOT__Nanod__v19;
        CData/*0:0*/ __VdlyVal__tb_xeno__DOT__main_board__DOT__cpu__DOT__Nanod__v20;
        CData/*0:0*/ __VdlySet__tb_xeno__DOT__main_board__DOT__cpu__DOT__Nanod__v20;
        CData/*0:0*/ __VdlyVal__tb_xeno__DOT__main_board__DOT__cpu__DOT__Nanod__v21;
        CData/*0:0*/ __VdlySet__tb_xeno__DOT__main_board__DOT__cpu__DOT__Nanod__v21;
        CData/*0:0*/ __VdlyVal__tb_xeno__DOT__main_board__DOT__cpu__DOT__Nanod__v22;
        CData/*0:0*/ __VdlySet__tb_xeno__DOT__main_board__DOT__cpu__DOT__Nanod__v22;
        CData/*0:0*/ __VdlyVal__tb_xeno__DOT__main_board__DOT__cpu__DOT__Nanod__v23;
        CData/*0:0*/ __VdlySet__tb_xeno__DOT__main_board__DOT__cpu__DOT__Nanod__v23;
        CData/*0:0*/ __VdlyVal__tb_xeno__DOT__main_board__DOT__cpu__DOT__Nanod__v24;
        CData/*0:0*/ __VdlySet__tb_xeno__DOT__main_board__DOT__cpu__DOT__Nanod__v24;
        CData/*0:0*/ __VdlyVal__tb_xeno__DOT__main_board__DOT__cpu__DOT__Nanod__v25;
        CData/*0:0*/ __VdlySet__tb_xeno__DOT__main_board__DOT__cpu__DOT__Nanod__v25;
        CData/*0:0*/ __VdlyVal__tb_xeno__DOT__main_board__DOT__cpu__DOT__Nanod__v26;
        CData/*0:0*/ __VdlySet__tb_xeno__DOT__main_board__DOT__cpu__DOT__Nanod__v26;
        CData/*0:0*/ __VdlyVal__tb_xeno__DOT__main_board__DOT__cpu__DOT__Nanod__v27;
        CData/*0:0*/ __VdlySet__tb_xeno__DOT__main_board__DOT__cpu__DOT__Nanod__v27;
        CData/*1:0*/ __VdlyVal__tb_xeno__DOT__main_board__DOT__cpu__DOT__Nanod__v28;
        CData/*0:0*/ __VdlySet__tb_xeno__DOT__main_board__DOT__cpu__DOT__Nanod__v28;
        CData/*0:0*/ __VdlyVal__tb_xeno__DOT__main_board__DOT__cpu__DOT__Nanod__v29;
        CData/*0:0*/ __VdlySet__tb_xeno__DOT__main_board__DOT__cpu__DOT__Nanod__v29;
        CData/*0:0*/ __VdlyVal__tb_xeno__DOT__main_board__DOT__cpu__DOT__Nanod__v30;
        CData/*0:0*/ __VdlySet__tb_xeno__DOT__main_board__DOT__cpu__DOT__Nanod__v30;
        CData/*0:0*/ __VdlyVal__tb_xeno__DOT__main_board__DOT__cpu__DOT__Nanod__v31;
        CData/*0:0*/ __VdlySet__tb_xeno__DOT__main_board__DOT__cpu__DOT__Nanod__v31;
        CData/*0:0*/ __VdlyVal__tb_xeno__DOT__main_board__DOT__cpu__DOT__Nanod__v32;
        CData/*0:0*/ __VdlySet__tb_xeno__DOT__main_board__DOT__cpu__DOT__Nanod__v32;
        CData/*0:0*/ __VdlyVal__tb_xeno__DOT__main_board__DOT__cpu__DOT__Nanod__v33;
        CData/*0:0*/ __VdlySet__tb_xeno__DOT__main_board__DOT__cpu__DOT__Nanod__v33;
        CData/*0:0*/ __VdlyVal__tb_xeno__DOT__main_board__DOT__cpu__DOT__Nanod__v34;
        CData/*0:0*/ __VdlySet__tb_xeno__DOT__main_board__DOT__cpu__DOT__Nanod__v34;
        CData/*0:0*/ __VdlyVal__tb_xeno__DOT__main_board__DOT__cpu__DOT__Nanod__v35;
        CData/*0:0*/ __VdlySet__tb_xeno__DOT__main_board__DOT__cpu__DOT__Nanod__v35;
        CData/*0:0*/ __VdlyVal__tb_xeno__DOT__main_board__DOT__cpu__DOT__Nanod__v36;
        CData/*0:0*/ __VdlySet__tb_xeno__DOT__main_board__DOT__cpu__DOT__Nanod__v36;
        CData/*0:0*/ __VdlyVal__tb_xeno__DOT__main_board__DOT__cpu__DOT__Nanod__v37;
        CData/*0:0*/ __VdlySet__tb_xeno__DOT__main_board__DOT__cpu__DOT__Nanod__v37;
        CData/*0:0*/ __VdlyVal__tb_xeno__DOT__main_board__DOT__cpu__DOT__Nanod__v38;
        CData/*0:0*/ __VdlySet__tb_xeno__DOT__main_board__DOT__cpu__DOT__Nanod__v38;
        CData/*0:0*/ __VdlyVal__tb_xeno__DOT__main_board__DOT__cpu__DOT__Nanod__v39;
        CData/*0:0*/ __VdlySet__tb_xeno__DOT__main_board__DOT__cpu__DOT__Nanod__v39;
        CData/*0:0*/ __VdlyVal__tb_xeno__DOT__main_board__DOT__cpu__DOT__Nanod__v40;
        CData/*0:0*/ __VdlySet__tb_xeno__DOT__main_board__DOT__cpu__DOT__Nanod__v40;
        CData/*0:0*/ __VdlyVal__tb_xeno__DOT__main_board__DOT__cpu__DOT__Nanod__v41;
        CData/*0:0*/ __VdlySet__tb_xeno__DOT__main_board__DOT__cpu__DOT__Nanod__v41;
    };
    struct {
        CData/*0:0*/ __VdlyVal__tb_xeno__DOT__main_board__DOT__cpu__DOT__Nanod__v42;
        CData/*0:0*/ __VdlySet__tb_xeno__DOT__main_board__DOT__cpu__DOT__Nanod__v42;
        CData/*0:0*/ __VdlyVal__tb_xeno__DOT__main_board__DOT__cpu__DOT__Nanod__v43;
        CData/*0:0*/ __VdlySet__tb_xeno__DOT__main_board__DOT__cpu__DOT__Nanod__v43;
        CData/*0:0*/ __VdlyVal__tb_xeno__DOT__main_board__DOT__cpu__DOT__Nanod__v44;
        CData/*0:0*/ __VdlySet__tb_xeno__DOT__main_board__DOT__cpu__DOT__Nanod__v44;
        CData/*0:0*/ __VdlyVal__tb_xeno__DOT__main_board__DOT__cpu__DOT__Nanod__v45;
        CData/*0:0*/ __VdlySet__tb_xeno__DOT__main_board__DOT__cpu__DOT__Nanod__v45;
        CData/*0:0*/ __VstlDidInit;
        CData/*0:0*/ __VstlFirstIteration;
        CData/*0:0*/ __VstlPhaseResult;
        CData/*0:0*/ __Vtrigprevexpr___TOP__clk__0;
        CData/*0:0*/ __Vtrigprevexpr___TOP__reset__0;
        CData/*0:0*/ __VicoDidInit;
        CData/*0:0*/ __VicoPhaseResult;
        CData/*0:0*/ __Vtrigprevexpr___TOP__clk__1;
        CData/*0:0*/ __Vtrigprevexpr_h0102208c__1;
        CData/*0:0*/ __Vtrigprevexpr___TOP__tb_xeno__DOT__main_board__DOT__cpu__DOT____Vcellinp__nanoRom__clk__0;
        CData/*0:0*/ __VactDidInit;
        CData/*0:0*/ __VactPhaseResult;
        CData/*0:0*/ __VnbaPhaseResult;
        VL_IN16(in0,15,0);
        VL_IN16(in1,15,0);
        VL_IN16(dsw,15,0);
        VL_OUT16(ctrl,15,0);
        VL_OUT16(dbg_palw,15,0);
        VL_OUT16(dbg_vramw,15,0);
        VL_OUT16(dbg_sprw,15,0);
        VL_OUT16(dbg_sphit,15,0);
        VL_OUT16(dbg_spblend,15,0);
        VL_OUT16(dbg_pal_data,15,0);
        SData/*15:0*/ tb_xeno__DOT__vram_q;
        SData/*15:0*/ tb_xeno__DOT__sprram_q;
        SData/*15:0*/ tb_xeno__DOT__main_board__DOT__cpu_din;
        SData/*15:0*/ tb_xeno__DOT__main_board__DOT__ram_q;
        SData/*10:0*/ tb_xeno__DOT__main_board__DOT__line_cnt;
        SData/*9:0*/ tb_xeno__DOT__main_board__DOT__cpu__DOT__microAddr;
        SData/*9:0*/ tb_xeno__DOT__main_board__DOT__cpu__DOT__nma;
        SData/*8:0*/ tb_xeno__DOT__main_board__DOT__cpu__DOT__nanoAddr;
        SData/*15:0*/ tb_xeno__DOT__main_board__DOT__cpu__DOT__psw;
        SData/*15:0*/ tb_xeno__DOT__main_board__DOT__cpu__DOT__ftu;
        SData/*15:0*/ tb_xeno__DOT__main_board__DOT__cpu__DOT__Irc;
        SData/*15:0*/ tb_xeno__DOT__main_board__DOT__cpu__DOT__Ir;
        SData/*15:0*/ tb_xeno__DOT__main_board__DOT__cpu__DOT__Ird;
        SData/*15:0*/ tb_xeno__DOT__main_board__DOT__cpu__DOT__alue;
        SData/*15:0*/ tb_xeno__DOT__main_board__DOT__cpu__DOT__excUnit__DOT__dbin;
        SData/*15:0*/ tb_xeno__DOT__main_board__DOT__cpu__DOT__excUnit__DOT__dcrOutput;
        SData/*15:0*/ tb_xeno__DOT__main_board__DOT__cpu__DOT__excUnit__DOT__PcL;
        SData/*15:0*/ tb_xeno__DOT__main_board__DOT__cpu__DOT__excUnit__DOT__PcH;
        SData/*15:0*/ tb_xeno__DOT__main_board__DOT__cpu__DOT__excUnit__DOT__Ath;
        SData/*15:0*/ tb_xeno__DOT__main_board__DOT__cpu__DOT__excUnit__DOT__Atl;
        SData/*15:0*/ tb_xeno__DOT__main_board__DOT__cpu__DOT__excUnit__DOT__Dbl;
        SData/*15:0*/ tb_xeno__DOT__main_board__DOT__cpu__DOT__excUnit__DOT__Dbh;
        SData/*15:0*/ tb_xeno__DOT__main_board__DOT__cpu__DOT__excUnit__DOT__Abh;
        SData/*15:0*/ tb_xeno__DOT__main_board__DOT__cpu__DOT__excUnit__DOT__Abl;
        SData/*15:0*/ tb_xeno__DOT__main_board__DOT__cpu__DOT__excUnit__DOT__Abd;
        SData/*15:0*/ tb_xeno__DOT__main_board__DOT__cpu__DOT__excUnit__DOT__Dbd;
        SData/*15:0*/ tb_xeno__DOT__main_board__DOT__cpu__DOT__excUnit__DOT__dblMux;
        SData/*15:0*/ tb_xeno__DOT__main_board__DOT__cpu__DOT__excUnit__DOT__dbhMux;
        SData/*15:0*/ tb_xeno__DOT__main_board__DOT__cpu__DOT__excUnit__DOT__abhMux;
        SData/*15:0*/ tb_xeno__DOT__main_board__DOT__cpu__DOT__excUnit__DOT__ablMux;
        SData/*15:0*/ tb_xeno__DOT__main_board__DOT__cpu__DOT__excUnit__DOT__abdMux;
        SData/*15:0*/ tb_xeno__DOT__main_board__DOT__cpu__DOT__excUnit__DOT__dbdMux;
        SData/*15:0*/ tb_xeno__DOT__main_board__DOT__cpu__DOT__excUnit__DOT__preAbh;
    };
    struct {
        SData/*15:0*/ tb_xeno__DOT__main_board__DOT__cpu__DOT__excUnit__DOT__preAbl;
        SData/*15:0*/ tb_xeno__DOT__main_board__DOT__cpu__DOT__excUnit__DOT__preAbd;
        SData/*15:0*/ tb_xeno__DOT__main_board__DOT__cpu__DOT__excUnit__DOT__preDbh;
        SData/*15:0*/ tb_xeno__DOT__main_board__DOT__cpu__DOT__excUnit__DOT__preDbl;
        SData/*15:0*/ tb_xeno__DOT__main_board__DOT__cpu__DOT__excUnit__DOT__preDbd;
        SData/*15:0*/ tb_xeno__DOT__main_board__DOT__cpu__DOT__excUnit__DOT__prenLatch;
        SData/*15:0*/ tb_xeno__DOT__main_board__DOT__cpu__DOT__excUnit__DOT__alub;
        SData/*15:0*/ tb_xeno__DOT__main_board__DOT__cpu__DOT__excUnit__DOT__dobInput;
        SData/*15:0*/ tb_xeno__DOT__main_board__DOT__cpu__DOT__excUnit__DOT__alu__DOT__aluLatch;
        SData/*15:0*/ tb_xeno__DOT__main_board__DOT__cpu__DOT__excUnit__DOT__alu__DOT__result;
        SData/*15:0*/ tb_xeno__DOT__main_board__DOT__cpu__DOT__excUnit__DOT__alu__DOT__row;
        SData/*15:0*/ tb_xeno__DOT__main_board__DOT__cpu__DOT__excUnit__DOT__alu__DOT__aOperand;
        SData/*15:0*/ tb_xeno__DOT__main_board__DOT__cpu__DOT__excUnit__DOT__alu__DOT__dOperand;
        SData/*15:0*/ tb_xeno__DOT__main_board__DOT__cpu__DOT__excUnit__DOT__alu__DOT__cRow;
        SData/*8:0*/ tb_xeno__DOT__main_board__DOT__cpu__DOT__excUnit__DOT__alu__DOT__aluCorf__DOT__htemp;
        SData/*15:0*/ tb_xeno__DOT__main_board__DOT__cpu__DOT__excUnit__DOT__dataIo__DOT__dob;
        SData/*15:0*/ tb_xeno__DOT__main_board__DOT__cpu__DOT__uaddrDecode__DOT__pla_lined__DOT__arIll;
        SData/*9:0*/ tb_xeno__DOT__main_board__DOT__cpu__DOT__uaddrDecode__DOT__pla_lined__DOT__scA3;
        SData/*9:0*/ tb_xeno__DOT__main_board__DOT__cpu__DOT__sequencer__DOT__uNma;
        SData/*9:0*/ tb_xeno__DOT__main_board__DOT__cpu__DOT__sequencer__DOT__grp1Nma;
        SData/*9:0*/ tb_xeno__DOT__video__DOT__hcnt;
        SData/*9:0*/ tb_xeno__DOT__video__DOT__vcnt;
        SData/*15:0*/ tb_xeno__DOT__video__DOT__vram_rq;
        SData/*10:0*/ tb_xeno__DOT__video__DOT__vram_raddr;
        SData/*15:0*/ tb_xeno__DOT__video__DOT__sprram_rq;
        SData/*10:0*/ tb_xeno__DOT__video__DOT__sprram_raddr;
        SData/*15:0*/ tb_xeno__DOT__video__DOT__bg_q0;
        SData/*15:0*/ tb_xeno__DOT__video__DOT__bg_q1;
        SData/*13:0*/ tb_xeno__DOT__video__DOT__bg_raddr;
        SData/*14:0*/ tb_xeno__DOT__video__DOT__spr_raddr;
        SData/*15:0*/ tb_xeno__DOT__video__DOT__bg_d0;
        SData/*15:0*/ tb_xeno__DOT__video__DOT__bg_d1;
        SData/*8:0*/ tb_xeno__DOT__video__DOT__bg_next_y;
        SData/*15:0*/ tb_xeno__DOT__video__DOT__sp_disp_q;
        SData/*8:0*/ tb_xeno__DOT__video__DOT__sp_idx;
        SData/*8:0*/ tb_xeno__DOT__video__DOT__sp_line;
        SData/*8:0*/ tb_xeno__DOT__video__DOT__sp_clr_addr;
        SData/*10:0*/ tb_xeno__DOT__video__DOT__sp_code;
        SData/*10:0*/ tb_xeno__DOT__video__DOT__sp_xs;
        SData/*8:0*/ tb_xeno__DOT__video__DOT__rgb9;
        SData/*15:0*/ tb_xeno__DOT__video__DOT__unnamedblk3__DOT__cur;
        SData/*10:0*/ __VcaseDecoderOut0;
        SData/*15:0*/ __Vtask_tb_xeno__DOT__main_board__DOT__cpu__DOT__excUnit__DOT__alu__DOT__mySubber__0__result;
        SData/*10:0*/ __Vdly__tb_xeno__DOT__main_board__DOT__line_cnt;
        SData/*9:0*/ __Vdly__tb_xeno__DOT__video__DOT__hcnt;
        SData/*9:0*/ __Vdly__tb_xeno__DOT__video__DOT__vcnt;
        SData/*15:0*/ __Vdly__tb_xeno__DOT__main_board__DOT__cpu__DOT__ftu;
        SData/*15:0*/ __VdlyVal__tb_xeno__DOT__main_board__DOT__cpu__DOT__excUnit__DOT__regs68H__v18;
        SData/*15:0*/ __VdlyVal__tb_xeno__DOT__main_board__DOT__cpu__DOT__excUnit__DOT__regs68H__v19;
        SData/*15:0*/ __VdlyVal__tb_xeno__DOT__main_board__DOT__cpu__DOT__excUnit__DOT__regs68L__v18;
        SData/*15:0*/ __VdlyVal__tb_xeno__DOT__main_board__DOT__cpu__DOT__excUnit__DOT__regs68L__v19;
        SData/*15:0*/ __VdlyVal__tb_xeno__DOT__main_board__DOT__cpu__DOT__excUnit__DOT__regs68L__v21;
        SData/*15:0*/ __VdlyVal__tb_xeno__DOT__main_board__DOT__cpu__DOT__excUnit__DOT__regs68L__v22;
        SData/*15:0*/ __VdlyVal__tb_xeno__DOT__main_board__DOT__cpu__DOT__excUnit__DOT__regs68L__v23;
        SData/*15:0*/ __VdlyVal__tb_xeno__DOT__main_board__DOT__cpu__DOT__excUnit__DOT__regs68L__v25;
        SData/*15:0*/ __Vtrigprevexpr___TOP__in0__0;
        SData/*15:0*/ __Vtrigprevexpr___TOP__in1__0;
        SData/*15:0*/ __Vtrigprevexpr___TOP__dsw__0;
        VL_OUT(dbg_addr,23,0);
        IData/*16:0*/ tb_xeno__DOT__acc;
        IData/*23:0*/ tb_xeno__DOT__st_cnt;
        IData/*31:0*/ tb_xeno__DOT__main_board__DOT__cpu__DOT__tState;
        VlWide<3>/*67:0*/ tb_xeno__DOT__main_board__DOT__cpu__DOT__nanoLatch;
        VlWide<3>/*67:0*/ tb_xeno__DOT__main_board__DOT__cpu__DOT__nanoOutput;
    };
    struct {
        IData/*16:0*/ tb_xeno__DOT__main_board__DOT__cpu__DOT__microLatch;
        IData/*16:0*/ tb_xeno__DOT__main_board__DOT__cpu__DOT__microOutput;
        IData/*31:0*/ tb_xeno__DOT__main_board__DOT__cpu__DOT__excUnit__DOT__auReg;
        IData/*31:0*/ tb_xeno__DOT__main_board__DOT__cpu__DOT__excUnit__DOT__aob;
        IData/*31:0*/ tb_xeno__DOT__main_board__DOT__cpu__DOT__excUnit__DOT__auInpMux;
        IData/*16:0*/ tb_xeno__DOT__main_board__DOT__cpu__DOT__excUnit__DOT__aulow;
        IData/*31:0*/ tb_xeno__DOT__main_board__DOT__cpu__DOT__excUnit__DOT__alu__DOT__shftResult;
        IData/*16:0*/ tb_xeno__DOT__main_board__DOT__cpu__DOT__excUnit__DOT__alu__DOT__mySubber__Vstatic__rtemp;
        IData/*31:0*/ tb_xeno__DOT__main_board__DOT__cpu__DOT__busArbiter__DOT__dmaPhase;
        IData/*31:0*/ tb_xeno__DOT__main_board__DOT__cpu__DOT__busArbiter__DOT__next;
        IData/*31:0*/ tb_xeno__DOT__main_board__DOT__cpu__DOT__busControl__DOT__busPhase;
        IData/*31:0*/ tb_xeno__DOT__main_board__DOT__cpu__DOT__busControl__DOT__next;
        IData/*30:0*/ __VcaseDecoderOut1;
        IData/*30:0*/ __VcaseDecoderOut2;
        IData/*30:0*/ __VcaseDecoderOut3;
        IData/*30:0*/ __VcaseDecoderOut4;
        IData/*30:0*/ __VcaseDecoderOut5;
        IData/*30:0*/ __VcaseDecoderOut6;
        IData/*30:0*/ __VcaseDecoderOut7;
        IData/*30:0*/ __VcaseDecoderOut8;
        IData/*30:0*/ __VcaseDecoderOut9;
        IData/*30:0*/ __VcaseDecoderOut10;
        IData/*30:0*/ __VcaseDecoderOut11;
        IData/*30:0*/ __VcaseDecoderOut12;
        IData/*30:0*/ __VcaseDecoderOut13;
        IData/*30:0*/ __VcaseDecoderOut14;
        IData/*30:0*/ __VcaseDecoderOut15;
        IData/*30:0*/ __VcaseDecoderOut16;
        IData/*30:0*/ __VcaseDecoderOut17;
        IData/*30:0*/ __VcaseDecoderOut18;
        IData/*30:0*/ __VcaseDecoderOut19;
        IData/*30:0*/ __VcaseDecoderOut20;
        IData/*20:0*/ __VcaseDecoderOut21;
        IData/*20:0*/ __VcaseDecoderOut22;
        IData/*20:0*/ __VcaseDecoderOut23;
        IData/*20:0*/ __VcaseDecoderOut24;
        IData/*20:0*/ __VcaseDecoderOut25;
        IData/*20:0*/ __VcaseDecoderOut26;
        IData/*20:0*/ __VcaseDecoderOut27;
        IData/*20:0*/ __VcaseDecoderOut28;
        IData/*20:0*/ __VcaseDecoderOut29;
        IData/*20:0*/ __VcaseDecoderOut30;
        IData/*20:0*/ __VcaseDecoderOut31;
        IData/*20:0*/ __VcaseDecoderOut32;
        IData/*20:0*/ __VcaseDecoderOut33;
        IData/*20:0*/ __VcaseDecoderOut34;
        IData/*20:0*/ __VcaseDecoderOut35;
        IData/*20:0*/ __VcaseDecoderOut36;
        IData/*20:0*/ __VcaseDecoderOut37;
        IData/*20:0*/ __VcaseDecoderOut38;
        IData/*20:0*/ __VcaseDecoderOut39;
        IData/*20:0*/ __VcaseDecoderOut40;
        IData/*20:0*/ __VcaseDecoderOut41;
        IData/*20:0*/ __VcaseDecoderOut42;
        IData/*20:0*/ __VcaseDecoderOut43;
        IData/*20:0*/ __VcaseDecoderOut44;
        IData/*20:0*/ __VcaseDecoderOut45;
        IData/*20:0*/ __VcaseDecoderOut46;
        IData/*20:0*/ __VcaseDecoderOut47;
        IData/*20:0*/ __VcaseDecoderOut48;
        IData/*20:0*/ __VcaseDecoderOut49;
        IData/*20:0*/ __VcaseDecoderOut50;
        IData/*20:0*/ __VcaseDecoderOut51;
        IData/*20:0*/ __VcaseDecoderOut52;
    };
    struct {
        IData/*20:0*/ __VcaseDecoderOut53;
        IData/*20:0*/ __VcaseDecoderOut54;
        IData/*20:0*/ __VcaseDecoderOut55;
        IData/*20:0*/ __VcaseDecoderOut56;
        IData/*20:0*/ __VcaseDecoderOut57;
        IData/*20:0*/ __VcaseDecoderOut58;
        IData/*20:0*/ __VcaseDecoderOut59;
        IData/*20:0*/ __VcaseDecoderOut60;
        IData/*20:0*/ __VcaseDecoderOut61;
        IData/*20:0*/ __VcaseDecoderOut62;
        IData/*20:0*/ __VcaseDecoderOut63;
        IData/*20:0*/ __VcaseDecoderOut64;
        IData/*20:0*/ __VcaseDecoderOut65;
        IData/*20:0*/ __VcaseDecoderOut66;
        IData/*20:0*/ __VcaseDecoderOut67;
        IData/*20:0*/ __VcaseDecoderOut68;
        IData/*20:0*/ __VcaseDecoderOut69;
        IData/*20:0*/ __VcaseDecoderOut70;
        IData/*20:0*/ __VcaseDecoderOut71;
        IData/*20:0*/ __VcaseDecoderOut72;
        IData/*20:0*/ __VcaseDecoderOut73;
        IData/*20:0*/ __VcaseDecoderOut74;
        IData/*20:0*/ __VcaseDecoderOut75;
        IData/*20:0*/ __VcaseDecoderOut76;
        IData/*20:0*/ __VcaseDecoderOut77;
        IData/*20:0*/ __VcaseDecoderOut78;
        IData/*20:0*/ __VcaseDecoderOut79;
        IData/*20:0*/ __VcaseDecoderOut80;
        IData/*20:0*/ __VcaseDecoderOut81;
        IData/*20:0*/ __VcaseDecoderOut82;
        IData/*20:0*/ __VcaseDecoderOut83;
        IData/*20:0*/ __VcaseDecoderOut84;
        IData/*20:0*/ __VcaseDecoderOut85;
        IData/*20:0*/ __VcaseDecoderOut86;
        IData/*20:0*/ __VcaseDecoderOut87;
        IData/*20:0*/ __VcaseDecoderOut88;
        IData/*20:0*/ __VcaseDecoderOut89;
        IData/*20:0*/ __VcaseDecoderOut90;
        IData/*20:0*/ __VcaseDecoderOut91;
        IData/*20:0*/ __VcaseDecoderOut92;
        IData/*20:0*/ __VcaseDecoderOut93;
        IData/*20:0*/ __VcaseDecoderOut94;
        IData/*20:0*/ __VcaseDecoderOut95;
        IData/*20:0*/ __VcaseDecoderOut96;
        IData/*20:0*/ __VcaseDecoderOut97;
        IData/*20:0*/ __VcaseDecoderOut98;
        IData/*20:0*/ __VcaseDecoderOut99;
        IData/*20:0*/ __VcaseDecoderOut100;
        IData/*20:0*/ __VcaseDecoderOut101;
        IData/*20:0*/ __VcaseDecoderOut102;
        IData/*20:0*/ __VcaseDecoderOut103;
        IData/*20:0*/ __VcaseDecoderOut104;
        IData/*20:0*/ __VcaseDecoderOut105;
        IData/*20:0*/ __VcaseDecoderOut106;
        IData/*20:0*/ __VcaseDecoderOut107;
        IData/*20:0*/ __VcaseDecoderOut108;
        IData/*20:0*/ __VcaseDecoderOut109;
        IData/*20:0*/ __VcaseDecoderOut110;
        IData/*20:0*/ __VcaseDecoderOut111;
        IData/*20:0*/ __VcaseDecoderOut112;
        IData/*20:0*/ __VcaseDecoderOut113;
        IData/*31:0*/ __VactIterCount;
        VlUnpacked<SData/*15:0*/, 131072> tb_xeno__DOT__rom;
        VlUnpacked<SData/*15:0*/, 8192> tb_xeno__DOT__main_board__DOT__ram;
    };
    struct {
        VlUnpacked<SData/*15:0*/, 18> tb_xeno__DOT__main_board__DOT__cpu__DOT__excUnit__DOT__regs68L;
        VlUnpacked<SData/*15:0*/, 18> tb_xeno__DOT__main_board__DOT__cpu__DOT__excUnit__DOT__regs68H;
        VlUnpacked<SData/*9:0*/, 16> tb_xeno__DOT__main_board__DOT__cpu__DOT__uaddrDecode__DOT__pla_lined__DOT__arA1;
        VlUnpacked<SData/*9:0*/, 16> tb_xeno__DOT__main_board__DOT__cpu__DOT__uaddrDecode__DOT__pla_lined__DOT__arA23;
        VlUnpacked<IData/*16:0*/, 1024> tb_xeno__DOT__main_board__DOT__cpu__DOT__uRom__DOT__uRam;
        VlUnpacked<VlWide<3>/*67:0*/, 336> tb_xeno__DOT__main_board__DOT__cpu__DOT__nanoRom__DOT__nRam;
        VlUnpacked<CData/*7:0*/, 3> tb_xeno__DOT__main_board__DOT__ptm__DOT__cr;
        VlUnpacked<SData/*15:0*/, 3> tb_xeno__DOT__main_board__DOT__ptm__DOT__latch;
        VlUnpacked<SData/*15:0*/, 3> tb_xeno__DOT__main_board__DOT__ptm__DOT__cnt;
        VlUnpacked<CData/*7:0*/, 3> tb_xeno__DOT__main_board__DOT__ptm__DOT__lsb_buf;
        VlUnpacked<SData/*15:0*/, 4096> tb_xeno__DOT__video__DOT__vram;
        VlUnpacked<SData/*15:0*/, 4096> tb_xeno__DOT__video__DOT__sprram;
        VlUnpacked<SData/*8:0*/, 64> tb_xeno__DOT__video__DOT__palette;
        VlUnpacked<SData/*15:0*/, 32768> tb_xeno__DOT__video__DOT__bg_rom;
        VlUnpacked<SData/*15:0*/, 32768> tb_xeno__DOT__video__DOT__spr_rom0;
        VlUnpacked<SData/*15:0*/, 32768> tb_xeno__DOT__video__DOT__spr_rom1;
        VlUnpacked<SData/*15:0*/, 32768> tb_xeno__DOT__video__DOT__spr_rom2;
        VlUnpacked<SData/*15:0*/, 32768> tb_xeno__DOT__video__DOT__spr_rom3;
        VlUnpacked<SData/*15:0*/, 4> tb_xeno__DOT__video__DOT__spr_q;
        VlUnpacked<VlUnpacked<CData/*6:0*/, 512>, 2> tb_xeno__DOT__video__DOT__bg_lbuf;
        VlUnpacked<VlUnpacked<SData/*15:0*/, 512>, 2> tb_xeno__DOT__video__DOT__sp_lbuf;
        VlUnpacked<VlUnpacked<SData/*15:0*/, 2>, 4> tb_xeno__DOT__video__DOT__sp_row;
        VlUnpacked<QData/*63:0*/, 2> __VstlTriggered;
        VlUnpacked<QData/*63:0*/, 2> __VicoTriggered;
        VlUnpacked<QData/*63:0*/, 1> __VactTriggered;
        VlUnpacked<QData/*63:0*/, 1> __VnbaTriggered;
    };
    Vtb_xeno_s_clks__struct__0 tb_xeno__DOT__main_board__DOT__cpu__DOT__Clks;
    Vtb_xeno_s_nanod__struct__0 tb_xeno__DOT__main_board__DOT__cpu__DOT__Nanod;
    Vtb_xeno_s_irdecod__struct__0 tb_xeno__DOT__main_board__DOT__cpu__DOT__Irdecod;
    Vtb_xeno_s_nanod__struct__0 __Vtrigprevexpr___TOP__tb_xeno__DOT__main_board__DOT__cpu__DOT__Nanod__0;
    Vtb_xeno_s_irdecod__struct__0 __Vtrigprevexpr___TOP__tb_xeno__DOT__main_board__DOT__cpu__DOT__Irdecod__0;
    Vtb_xeno_s_nanod__struct__0 __Vtrigprevexpr___TOP__tb_xeno__DOT__main_board__DOT__cpu__DOT__Nanod__1;
    Vtb_xeno_s_irdecod__struct__0 __Vtrigprevexpr___TOP__tb_xeno__DOT__main_board__DOT__cpu__DOT__Irdecod__1;

    // INTERNAL VARIABLES
    Vtb_xeno__Syms* vlSymsp;
    const char* vlNamep;

    // CONSTRUCTORS
    Vtb_xeno___024root(Vtb_xeno__Syms* symsp, const char* namep);
    ~Vtb_xeno___024root();
    VL_UNCOPYABLE(Vtb_xeno___024root);

    // INTERNAL METHODS
    void __Vconfigure(bool first);
};


#endif  // guard
